//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4961
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IU.Contabilidad.TipoMovimiento {
    
    
    public partial class ListarTiposDeMovimientos {
        
        /// <summary>
        /// form1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated conexion.
        /// To modify move conexion declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
        
        /// <summary>
        /// ControlListar1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated conexion.
        /// To modify move conexion declaration from designer file to code-behind file.
        /// </remarks>
        protected global::IU.Generico.ControlListar ControlListar1;
    }
}
