///////////////////////////////////////////////////////////
//  PuestoDeTrabajo.cs
//  Implementation of the Class PuestoDeTrabajo
//  Generated by Enterprise Architect
//  Created on:      17-Ago-2011 12:04:14 p.m.
//  Original author: Luciano Rasente
///////////////////////////////////////////////////////////

using AdministradorGeneral;
using System;
using ModuloSoporte;

namespace AdministradorGeneral.Empresas
{
    /// <summary>
    /// Representa un puesto de trabajo en una determinada empresa.
    /// </summary>
	public class PuestoDeTrabajo : ClaseBaseHabilitable<long>
    {
        #region Atributos y propiedades

        private Empresa empresa;
        /// <summary>
        /// Empresa a la cual pertenece el puesto de trabajo.
        /// </summary>
        public Empresa Empresa
        {
            get { return empresa; }
            set { empresa = value; }
        }

        #endregion

        #region Constructores
        public PuestoDeTrabajo()
            : this(0, "", false, null)
        {

        }

        /// <summary>
        /// Constructor.
        /// </summary>
        /// <param name="cod"></param>
        /// <param name="descripcion"></param>
        /// <param name="habilitado"></param>
        /// <param name="empresa"></param>
		public PuestoDeTrabajo(long cod, string descripcion, bool habilitado, Empresa empresa)
        {
            Cod = cod;
            Descripcion = descripcion;
            Habilitado = habilitado;
            Empresa = empresa;
        }

        #endregion
    }//end PuestoDeTrabajo
}//end namespace Empresas